import {
  AlertCircle,
  Armchair,
  ArrowUpDown,
  Bath,
  BedDouble,
  Bell,
  Briefcase,
  Calendar,
  Car,
  Check,
  Coffee,
  CookingPot,
  Droplet,
  Flame,
  Gamepad2,
  GraduationCap,
  HeartPulse,
  KeyRound,
  Laptop,
  Lock,
  LockKeyhole,
  Map,
  MessageSquare,
  Minus,
  Package,
  PawPrint,
  Play,
  Shield,
  ShieldAlert,
  Shirt,
  Snowflake,
  SprayCan,
  Sun,
  Tag,
  Thermometer,
  Trees,
  Tv,
  UtensilsCrossed,
  Utensils,
  Video,
  Volume2,
  Waves,
  Wifi,
  Wind,
  Sparkles,
  Sandwich,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  // Amenity icons
  utensils: Utensils,
  wifi: Wifi,
  laptop: Laptop,
  car: Car,
  waves: Waves,
  bath: Bath,
  "paw-print": PawPrint,
  cctv: Video,
  "thermometer-snowflake": Thermometer,
  tv: Tv,
  "washing-machine": Waves,
  refrigerator: Package,
  microwave: Minus,
  "cooking-pot": CookingPot,
  coffee: Coffee,
  sandwich: Sandwich,
  "utensils-crossed": UtensilsCrossed,
  sparkles: Sparkles,
  shirt: Shirt,
  wind: Wind,
  droplet: Droplet,
  "bed-double": BedDouble,
  "heart-pulse": HeartPulse,
  "shield-alert": ShieldAlert,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  armchair: Armchair,
  trees: Trees,
  flame: Flame,
  play: Play,
  speaker: Volume2,
  "gamepad-2": Gamepad2,
  "arrow-up-down": ArrowUpDown,
  // Highlight icons
  "alert-circle": AlertCircle,
  bell: Bell,
  sun: Sun,
  snowflake: Snowflake,
  key: KeyRound,
  // Host fact icons
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  // Policy icons
  calendar: Calendar,
  shield: Shield,
  // Rating category icons
  spray: SprayCan,
  check: Check,
  message: MessageSquare,
  map: Map,
  tag: Tag,
};

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Bell;
}
