import {
  AlertCircle,
  Bath,
  Bell,
  Briefcase,
  Calendar,
  Car,
  Check,
  GraduationCap,
  KeyRound,
  Laptop,
  Map,
  MessageSquare,
  PawPrint,
  Shield,
  Snowflake,
  SprayCan,
  Sun,
  Tag,
  Video,
  Waves,
  Wifi,
  Utensils,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  wifi: Wifi,
  laptop: Laptop,
  car: Car,
  waves: Waves,
  bath: Bath,
  "paw-print": PawPrint,
  cctv: Video,
  "alert-circle": AlertCircle,
  bell: Bell,
  sun: Sun,
  snowflake: Snowflake,
  key: KeyRound,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  calendar: Calendar,
  shield: Shield,
  spray: SprayCan,
  check: Check,
  message: MessageSquare,
  map: Map,
  tag: Tag,
};

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Bell;
}
